### ISSUE TITLE
Add unicode block character support

### ISSUE THREAD

**Issue by klopsi** [rossy/img2xterm#12]
How about a version that can do 2x2 pixel blocks per character? Using the unicode  ▘ ▝ ▖ ▗ ▟ ▙ ▜ ▛ ▚ ▞ ▉ 
Of course you do lose the ability to set color of each pixel independently, being limited to one FG and one BG color per 4-pixel block, but you get so much more detail, see:
<img>https://abload.de/img/higgscapmvy6w.png</img>

**Comment by rossy** [comment]
That's a good idea, but it also adds other complexities. For example, the half blocks ▀▄▉ are _almost_ square with most terminal fonts, but I think the quarter blocks are less square, so it wouldn't look as good with pixel art. The colour thing is a killer too, because it's pretty easy to pick optimal colours when you can set each colour independently, but it would need more complicated code if it had to find an optimal 2-colour palette for each block of four pixels.

Since this is a big change and this project is somewhat unmaintained at the moment, I can't promise anything, but I'll keep it in mind.

**Comment by klopsi** [comment]
ok if you don't mind, i'll link to my unicode block character exporter and related tools 
https://github.com/klopsi/unicolexport

cheers!
